version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@vuepress/plugin-back-to-top"
    versions:
    - 1.8.1
    - 1.8.2
  - dependency-name: "@vuepress/plugin-google-analytics"
    versions:
    - 1.8.1
    - 1.8.2
  - dependency-name: "@vuepress/plugin-pwa"
    versions:
    - 1.8.1
    - 1.8.2
  - dependency-name: "@vuepress/plugin-last-updated"
    versions:
    - 1.8.1
    - 1.8.2
  - dependency-name: "@vuepress/plugin-nprogress"
    versions:
    - 1.8.1
  - dependency-name: vuepress
    versions:
    - 1.8.1
