import { fontFamilies, type FontFamilyConfig } from "../fonts.config.ts";

const PUBLIC_FONTS_DIR = `${Deno.cwd()}/public/fonts`;
const CSS_OUTPUT_FILE = `${PUBLIC_FONTS_DIR}/fonts.css`;

function toKebabCase(value: string): string {
	return value
		.trim()
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-+|-+$/g, "");
}

function buildBunnyCssUrl(family: FontFamilyConfig): string {
	const familyName = family.name.trim().replace(/\s+/g, "+");
	const weights = [...new Set(family.weights)].sort((a, b) => a - b).join(",");
	return `https://fonts.bunny.net/css?family=${familyName}:${weights}`;
}

async function downloadFile(url: string, outputPath: string): Promise<void> {
	const response = await fetch(url);
	if (!response.ok) {
		throw new Error(`Failed download (${response.status}) for ${url}`);
	}

	const bytes = new Uint8Array(await response.arrayBuffer());
	await Deno.writeFile(outputPath, bytes);
}

function rewriteCssUrls(
	css: string,
	familySlug: string,
	urlMap: Map<string, string>,
): string {
	return css.replace(/url\(([^)]+)\)/g, (fullMatch, rawUrl: string) => {
		const cleaned = rawUrl.trim().replace(/^['"]|['"]$/g, "");
		const localFile = urlMap.get(cleaned);
		if (!localFile) {
			return fullMatch;
		}
		return `url("/fonts/${familySlug}/${localFile}")`;
	});
}

async function processBunnyFamily(family: FontFamilyConfig): Promise<string> {
	const familySlug = toKebabCase(family.name);
	const targetDir = `${PUBLIC_FONTS_DIR}/${familySlug}`;
	await Deno.mkdir(targetDir, { recursive: true });

	const cssUrl = buildBunnyCssUrl(family);
	const cssResponse = await fetch(cssUrl);
	if (!cssResponse.ok) {
		throw new Error(
			`Failed fetching css (${cssResponse.status}) for ${family.name}`,
		);
	}

	const remoteCss = await cssResponse.text();
	const fontUrlMatches = [...remoteCss.matchAll(/url\(([^)]+)\)/g)];
	const uniqueFontUrls = [
		...new Set(
			fontUrlMatches.map((match) =>
				match[1].trim().replace(/^['"]|['"]$/g, ""),
			),
		),
	];

	const urlToFile = new Map<string, string>();
	for (const [index, fontUrl] of uniqueFontUrls.entries()) {
		const parsedUrl = new URL(fontUrl);
		const pathname = parsedUrl.pathname.toLowerCase();
		const extension = pathname.endsWith(".woff2")
			? "woff2"
			: pathname.endsWith(".woff")
				? "woff"
				: pathname.endsWith(".ttf")
					? "ttf"
					: pathname.endsWith(".otf")
						? "otf"
						: "bin";
		const filename = `${familySlug}-${String(index + 1).padStart(2, "0")}.${extension}`;
		await downloadFile(fontUrl, `${targetDir}/${filename}`);
		urlToFile.set(fontUrl, filename);
	}

	return rewriteCssUrls(remoteCss, familySlug, urlToFile);
}

async function main(): Promise<void> {
	await Deno.mkdir(PUBLIC_FONTS_DIR, { recursive: true });

	const cssBlocks: string[] = [];
	for (const family of fontFamilies) {
		if (family.provider !== "bunny") {
			throw new Error(`Unsupported provider: ${family.provider}`);
		}

		console.log(`Downloading "${family.name}" from ${family.provider}...`);
		cssBlocks.push(await processBunnyFamily(family));
	}

	const banner = "/* Generated by scripts/fonts-download.ts */\n";
	await Deno.writeTextFile(
		CSS_OUTPUT_FILE,
		`${banner}${cssBlocks.join("\n\n")}\n`,
	);
	console.log(`Fonts downloaded to: ${PUBLIC_FONTS_DIR}`);
	console.log(`CSS generated at: ${CSS_OUTPUT_FILE}`);
}

await main();
