# Build the website to produce the static files,
# also serves as a test for regressions

name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [26.1.0]

    steps:
      - uses: actions/checkout@v6
      - name: 💻 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📦 Install dependencies
        run: npm ci

      - name: 📝 Run unit tests
        run: npm run test

      - name: 🏗️ Build static website
        run: npm run generate
