# Build the website to produce the static files,
# also serves as a test for regressions

name: Build

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: 💻 Use Deno v2
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.
          cache: true

      - name: 📝 Run tests
        run: deno task test

      - name: 🏗️ Build static website
        run: deno task build
